### ISSUE TITLE
arm cannot start

### ISSUE THREAD

**Issue by mathslimin** [wtdcode/DebianOnQEMU#1]
qemu-system-arm -m 2048 -M virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 \
    -kernel vmlinuz -initrd initrd.img -append "root=/dev/mmcblk0 net.ifnames=0 biosdevname=0 nokaslr" \
    -hda rootfs.qcow2 -net nic -net tap,ifname=tap108,script="./qemu-brup",downscript="./qemu-brdown" \
    -nographic

Begin: Loading essential drivers ... done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... done.
Begin: Waiting for root file system ... Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
done.
Gave up waiting for root file system device.  Common problems:
 - Boot args (cat /proc/cmdline)
   - Check rootdelay= (did the system wait long enough?)
 - Missing modules (cat /proc/modules; ls /dev)
ALERT!  /dev/mmcblk0 does not exist.  Dropping to a shell!

**Comment by wtdcode** [comment]
Hello, thanks for your issue. What `initrd` and `vmlinuz` do you download?

**Comment by mathslimin** [comment]
I use arm, use this command
qemu-system-arm -m 2048 -M virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 \                                                                                                                                                         
  -kernel ./vmlinuz-5.10.0-13-armmp \                                                                                                                                                                                         
  -initrd ./initrd.img-5.10.0-13-armmp \                                                                                                                                                                                      
  -hda ./debian-bullseye-armhf-armmp.qcow2 \                                                                                                                                                                                  
  -append "root=/dev/vda rw console=ttyAMA0 rodata=n" \                                                                                                                                                                       
  -nographic    

my linux is ubuntu 18.04, not support kvm

**Comment by luckydevil13** [comment]
same here

a@DESKTOP-wsl:~$ qemu-system-x86_64 -m 512 -kernel ./vmlinuz-5.10.0-16-armmp -initrd ./initrd.img-5.10.0-16-armmp -append "console=ttyS0 debug root=/dev/sda net.ifnames=0"  -hda ./debian-bullseye-armhf-armmp.qcow2 -nographic -nic user,model=virtio-net-pci,hostfwd=tcp::5555-:22
qemu: linux kernel too old to load a ram disk

**Comment by wtdcode** [comment]
> qemu-system-arm -m 2048 -M virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 \
> -kernel ./vmlinuz-5.10.0-13-armmp \
> -initrd ./initrd.img-5.10.0-13-armmp \
> -hda ./debian-bullseye-armhf-armmp.qcow2 \
> -append "root=/dev/vda rw console=ttyAMA0 rodata=n" \
> -nographic

I tried your command line and it works fine on my machine (using `5.10.0-16-armmp`)?

**Comment by teroz** [comment]
> > qemu-system-arm -m 2048 -M virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 
> > -kernel ./vmlinuz-5.10.0-13-armmp 
> > -initrd ./initrd.img-5.10.0-13-armmp 
> > -hda ./debian-bullseye-armhf-armmp.qcow2 
> > -append "root=/dev/vda rw console=ttyAMA0 rodata=n" 
> > -nographic
> 
> I tried your command line and it works fine on my machine (using `5.10.0-16-armmp`)?

This didn't work for me either but this did
```bash
qemu-system-arm -m 2048 -M virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 -kernel ./vmlinuz-5.10.0-22-armmp -initrd ./initrd.img-5.10.0-22-armmp \
-drive if=none,file=debian-bullseye-armhf-armmp.qcow2,id=hd0 -device virtio-blk-device,drive=hd0 \
-append "root=/dev/vda rw console=ttyAMA0 rodata=n" \
-nographic \
```

**Comment by baiwfg2** [comment]
> > qemu-system-arm -m 2048 -M virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 
> > -kernel ./vmlinuz-5.10.0-13-armmp 
> > -initrd ./initrd.img-5.10.0-13-armmp 
> > -hda ./debian-bullseye-armhf-armmp.qcow2 
> > -append "root=/dev/vda rw console=ttyAMA0 rodata=n" 
> > -nographic
> 
> I tried your command line and it works fine on my machine (using `5.10.0-16-armmp`)?

Works for me too. But I add net part:
```
 qemu-system-arm -m 2048 -M virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 -kernel /f/vmlinuz-5.10.0-22-armmp -initrd /f/initrd.img-5.10.0-22-armmp -hda /f/debian-bullseye-armhf-armmp.qcow2 -append "root=/dev/vda rw console=ttyAMA0 rodata=n" -nographic -net nic -net user,hostfwd=tcp::2223-:22
```

It only shows (initramfs) command line, and I cannot ssh to the machine. Why is that ?

**Comment by wtdcode** [comment]
@baiwfg2 Your disk is not mounted correctly so Debian fails to boot

**Comment by wtdcode** [comment]
I updated all start command lines and pushed a docker to avoid qemu regression. Please check the latest release and README!
