### ISSUE TITLE
Arm cannot start: Gave up waiting for root file system device

### ISSUE THREAD

**Issue by PanosDgs** [wtdcode/DebianOnQEMU#3]
Hello.

I tried setting up the debian on armhf. But I do not know what I should specify as **-append** flag when starting QEMU. It keeps saying:
![image](https://user-images.githubusercontent.com/95704409/203076005-cf4ccbbc-3137-441b-bfdf-77f00db821ac.png)

Any ideas?

**Comment by wtdcode** [comment]
Did you append `root=/dev/vda`?

**Comment by PanosDgs** [comment]
Yes. Generally I dont know what I should append there. An explaination would be appreciated.

**Comment by wtdcode** [comment]
> Yes. Generally I dont know what I should append there. An explaination would be appreciated.

Could you try options in #1 ?

**Comment by PanosDgs** [comment]
> > Yes. Generally I dont know what I should append there. An explaination would be appreciated.
> 
> Could you try options in #1 ?

Already did that. Still not working. The append flag tells the debian grub where to find the root file system, right?

**Comment by wtdcode** [comment]
> > > Yes. Generally I dont know what I should append there. An explaination would be appreciated.
> > 
> > 
> > Could you try options in #1 ?
> 
> Already did that. Still not working. The append flag tells the debian grub where to find the root file system, right?

There is no grub for qemu to boot arm Linux. In other words, qemu itself plays the role of grub.

What errors do you get?

**Comment by PanosDgs** [comment]
> Hello.
> 
> I tried setting up the debian on armhf. But I do not know what I should specify as **-append** flag when starting QEMU. It keeps saying: ![image](https://user-images.githubusercontent.com/95704409/203076005-cf4ccbbc-3137-441b-bfdf-77f00db821ac.png)
> 
> Any ideas?

This is the error and it just drops a cell after that. It says it gave up on waiting for root file system device and that it cannot find the filepath that is specified on the -append flag. What do you specify as the root filepath?

**Comment by wtdcode** [comment]
Could you give the full command line and your qemu version?

**Comment by PanosDgs** [comment]
sudo qemu-system-arm -machine virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 -nographic --append "root=/dev/vda" \
        -kernel ./vmlinuz-4.19.0-12-armmp-lpae -initrd ./initrd.img-4.19.0-12-armmp-lpae -m 1024 \
        -netdev tap,ifname=vmnic1,id=n0,script=no,downscript=no -device virtio-net-device,netdev=n0 \
        -drive file=debian.qcow2,if=none,format=qcow2,id=hd0 -device virtio-blk-device,drive=hd0


This is what I found here: https://blog.lazym.io/2021/04/16/Run-ARM-MIPS-Debian-on-QEMU/

Of course I have changed the kernel and initrd versions to the latest ones you have uploaded on releases.

**Comment by wtdcode** [comment]
> sudo qemu-system-arm -machine virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 -nographic --append "root=/dev/vda" -kernel ./vmlinuz-4.19.0-12-armmp-lpae -initrd ./initrd.img-4.19.0-12-armmp-lpae -m 1024 -netdev tap,ifname=vmnic1,id=n0,script=no,downscript=no -device virtio-net-device,netdev=n0 -drive file=debian.qcow2,if=none,format=qcow2,id=hd0 -device virtio-blk-device,drive=hd0
> 
> This is what I found here: https://blog.lazym.io/2021/04/16/Run-ARM-MIPS-Debian-on-QEMU/
> 
> Of course I have changed the kernel and initrd versions to the latest ones you have uploaded on releases.

Could you paste the actual command line?

**Comment by PanosDgs** [comment]
> Could you paste the actual command line?


> sudo qemu-system-arm -machine virt -cpu cortex-a15 -smp cpus=4,maxcpus=4 -nographic --append "root=/dev/vda" \
> -kernel ./vmlinuz-5.10.0-18-armmp -initrd ./initrd.img-5.10.0-18-armmp -m 1024 \
> -netdev tap,ifname=vmnic1,id=n0,script=no,downscript=no -device virtio-net-device,netdev=n0 \
> -drive file=debian-bullseye-armhf-armmp.qcow2,if=none,format=qcow2,id=hd0 -device virtio-blk-device,dr
ive=hd0

QEMU version: QEMU emulator version 4.2.1

**Comment by PanosDgs** [comment]
Basically I tried again today with the command I mentioned in the above comment and it worked. So I will close the issue. Thank you!!
